// ** Third Party Components
import axios from 'axios'

export let patientsData

// ** Get initial Data
axios.get('/api/patients/initial-data').then(response => {
  patientsData = response.data
})


export const insuranceTypes = [
  {label: "21st Century Insurance"},
  {label: "Acuity Insurance"},
  {label: "Aflac"},
  {label: "Allianz Life"},
  {label: "Allied Insurance"},
  {label: "Allstate"},
  {label: "American Automobile Association"},
  {label: "American Family Insurance"},
  {label: "American Income Life Insurance Company"},
  {label: "American International Group"},
  {label: "American National Insurance Company"},
  {label: "American Strategic Insurance"},
  {label: "Ameriprise Auto & Home Insurance"},
  {label: "Ameriprise Financial"},
  {label: "Ameritas Life Insurance Company"},
  {label: "Amica Mutual Insurance"},
  {label: "Amtrust Financial Services"},
  {label: "Applied Underwriters"},
  {label: "Arbella Insurance Group"},
  {label: "Assurant"},
  {label: "Assurity Life Insurance Company"},
  {label: "Auto-Owners Insurance"},
  {label: "AXA Equitable Life Insurance Company"},
  {label: "Bankers Life and Casualty Company"},
  {label: "Berkshire Hathaway"},
  {label: "Brotherhood Mutual Insurance Company"},
  {label: "CareSource"},
  {label: "Celina Insurance Group"},
  {label: "Chubb Corp"},
  {label: "Cincinnati Insurance Company"},
  {label: "Citizens Property Insurance Corporation"},
  {label: "CNA Financial"},
  {label: "CNO Financial Group"},
  {label: "Colonial Life & Accident Insurance Company"},
  {label: "Combined Insurance[36]"},
  {label: "Commerce Insurance Group"},
  {label: "Country Financial[37]"},
  {label: "Country-Wide Insurance Company"},
  {label: "Delta Dental"},
  {label: "Donegal Insurance Group"},
  {label: "Encompass Insurance Company"},
  {label: "Erie Insurance Group"},
  {label: "Esurance"},
  {label: "Evergreen USA RRG"},
  {label: "Farmers Insurance Group"},
  {label: "Federated Mutual Insurance Company"},
  {label: "First Insurance Company of Hawaii"},
  {label: "FM Global"},
  {label: "Foremost Insurance Group"},
  {label: "Frankenmuth Insurance"},
  {label: "GAINSCO"},
  {label: "GEICO"},
  {label: "General Re"},
  {label: "Genworth Financial"},
  {label: "Gerber Life Insurance Company"},
  {label: "Globe Life And Accident Insurance Company"},
  {label: "GMAC Insurance"},
  {label: "Gracy Title Company"},
  {label: "Grange Mutual Casualty Company"},
  {label: "The Guardian Life Insurance Company of America"},
  {label: "GuideOne Insurance"},
  {label: "Hagerty Insurance Agency"},
  {label: "Hanover Insurance"},
  {label: "The Hartford"},
  {label: "HCC Insurance Holdings"},
  {label: "Hiscox Small Business Insurance"},
  {label: "Horace Mann Educators Corporation"},
  {label: "IntelliQuote Insurance Services"},
  {label: "Ironshore"},
  {label: "K&K Insurance"},
  {label: "Kansas City Life Insurance Company"},
  {label: "Kemper Corporation"},
  {label: "Kentucky Farm Bureau"},
  {label: "Kentucky National Insurance Company"},
  {label: "Knights of Columbus"},
  {label: "Lemonade (insurance)"},
  {label: "Liberty Mutual"},
  {label: "Lincoln National Corporation"},
  {label: "Main Street America Insurance"},
  {label: "Manhattan Life Insurance Company"},
  {label: "Markel Corporation"},
  {label: "MassMutual"},
  {label: "Merchants Insurance Group"},
  {label: "Mercury Insurance Group"},
  {label: "MetLife"},
  {label: "Metromile"},
  {label: "Modern Woodmen of America"},
  {label: "Mutual of Omaha"},
  {label: "National Flood Insurance Program"},
  {label: "Nationwide Mutual Insurance Company"},
  {label: "New Jersey Manufacturers Insurance Company"},
  {label: "New York Life Insurance Company"},
  {label: "Next Insurance"},
  {label: "NJM Insurance Group"},
  {label: "The Norfolk & Dedham Group"},
  {label: "Northwestern Mutual"},
  {label: "Omega"},
  {label: "OneBeacon"},
  {label: "Oxford Health Plans"},
  {label: "Pacific Life"},
  {label: "PEMCO"},
  {label: "Penn Mutual"},
  {label: "Penn National Insurance"},
  {label: "Pennsylvania Lumbermens Mutual Insurance Company"},
  {label: "Philadelphia Contributionship for the Insurance of Houses from Loss by Fire"},
  {label: "Philadelphia Insurance Companies"},
  {label: "Physicians Mutual"},
  {label: "Plymouth Rock"},
  {label: "Primerica"},
  {label: "Principal Financial Group"},
  {label: "Progressive"},
  {label: "ProSight Specialty Insurance"},
  {label: "Protective Life"},
  {label: "Prudential Financial"},
  {label: "Pure Insurance"},
  {label: "QBE"},
  {label: "The Regence Group"},
  {label: "Reliance Insurance Company"},
  {label: "Reliance Partners"},
  {label: "RLI Corp."},
  {label: "Safe Auto Insurance Company"},
  {label: "Safeco"},
  {label: "Safeway Insurance Group"},
  {label: "Securian Financial Group"},
  {label: "Selective Insurance"},
  {label: "Sentry Insurance"},
  {label: "Shelter Insurance"},
  {label: "Society Insurance"},
  {label: "Southern Aid and Insurance Company"},
  {label: "SquareTrade"},
  {label: "Standard Insurance Company"},
  {label: "State Auto Insurance Companies"},
  {label: "State Farm Insurance"},
  {label: "Summit Holdings"},
  {label: "Sun Life Financial"},
  {label: "Symetra"},
  {label: "The General"},
  {label: "The Travelers Companies"},
  {label: "TIAA-CREF"},
  {label: "Titan Insurance Company"},
  {label: "Tower Hill Insurance Group"},
  {label: "Transamerica Corporation"},
  {label: "Tricare"},
  {label: "Trupanion"},
  {label: "UPC Insurance"},
  {label: "Unum"},
  {label: "USAA"},
  {label: "Utica National Insurance Group"},
  {label: "West Coast Life"},
  {label: "Western & Southern Financial Group"},
  {label: "Western Mutual Insurance Group"},
  {label: "Westfield Insurance"},
  {label: "White Mountains Insurance Group"},
  {label: "XL Catlin"},
  {label: "Zurich Insurance Group"},
  {label: "Aflac"},
  {label: "Allianz Life"},
  {label: "Allstate"},
  {label: "American Family Insurance"},
  {label: "American Fidelity Assurance"},
  {label: "American Income Life Insurance Company"},
  {label: "Ameritas Life Insurance Company"},
  {label: "Amica Mutual Insurance"},
  {label: "Assurity Life Insurance Company"},
  {label: "AXA Equitable Life Insurance Company"},
  {label: "Bankers Life and Casualty"},
  {label: "Banner Life Insurance Company"},
  {label: "Colonial Life & Accident Insurance Company"},
  {label: "Colonial Penn"},
  {label: "Conseco"},
  {label: "Farmers Insurance Group"},
  {label: "Federal Life Insurance Company"},
  {label: "Garden State Life"},
  {label: "Genworth Financial"},
  {label: "The Great-West Life Assurance Company"},
  {label: "Gerber Life Insurance Company"},
  {label: "Globe Life And Accident Insurance Company"},
  {label: "The Guardian Life Insurance Company of America"},
  {label: "Horace Mann Educators Corporation"},
  {label: "ING Group"}, {label: "Jackson National Life"},
  {label: "John Hancock Life Insurance"},
  {label: "Kansas City Life Insurance Company"},
  {label: "Lincoln National Corporation"},
  {label: "Manhattan Life Insurance Company"},
  {label: "MEGA Life and Health Insurance"},
  {label: "MetLife"},
  {label: "Mutual of Omaha"},
  {label: "National Life Group"},
  {label: "National Western Life Insurance Company"},
  {label: "Nationwide Mutual Insurance Company"},
  {label: "New York Life Insurance Company"},
  {label: "Ohio National Financial Services Company"},
  {label: "Pacific Life"},
  {label: "Primerica"},
  {label: "Protective Life"},
  {label: "Prudential Financial"},
  {label: "Securian Financial Group"},
  {label: "Standard Insurance Company"},
  {label: "State Farm Insurance"},
  {label: "Thrivent Financial for Lutherans"},
  {label: "TIAA-CREF"},
  {label: "Transamerica Corporation"},
  {label: "UNIFI Companies"},
  {label: "United of Omaha"},
  {label: "Veterans Life Insurance"},
  {label: "Western & Southern Financial Group"},
  {label: "AARP"},
  {label: "Aetna"},
  {label: "American Family Insurance"},
  {label: "American National Insurance Company"},
  {label: "Amerigroup"},
  {label: "Anthem"},
  {label: "Blue Cross and Blue Shield Association"},
  {label: "CareSource"},
  {label: "Cambia Health Solutions"},
  {label: "Centene Corporation"},
  {label: "Cigna"},
  {label: "Coventry Health Care"},
  {label: "Delta Dental"},
  {label: "EmblemHealth"},
  {label: "Fortis"},
  {label: "Geisinger"},
  {label: "Golden Rule Insurance Company"},
  {label: "Group Health Cooperative"},
  {label: "Group Health Incorporated"},
  {label: "Harvard Pilgrim Health Care"},
  {label: "Health Net"},
  {label: "HealthMarkets"},
  {label: "HealthPartners"},
  {label: "HealthSpring"},
  {label: "Highmark"},
  {label: "Horace Mann Educators Corporation"},
  {label: "Humana"},
  {label: "Independence Blue Cross"},
  {label: "Kaiser Permanente"},
  {label: "Kaleida Health"},
  {label: "Liberty Medical"},
  {label: "LifeWise Health Plan of Oregon"}, {label: "MassHealth"},
  {label: "Medica"},
  {label: "Medical Mutual of Ohio"},
  {label: "MEGA Life and Health Insurance"}, {label: "Molina Healthcare"},
  {label: "Oscar Health"}, {label: "Oxford Health Plans"}, {label: "Premera Blue Cross"},
  {label: "Principal Financial Group"}, {label: "Shelter Insurance"}, {label: "State Farm"},
  {label: "Thrivent Financial for Lutherans"}, {label: "UnitedHealth Group"},
  {label: "Unitrin"}, {label: "Universal American Corporation"}, {label: "US Health Group"},
  {label: "Vantage Health Plan"}, {label: "WellCare"}
]