# Generated by Django 3.2.5 on 2021-07-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profiletemp',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
