# Generated by Django 3.2.5 on 2021-07-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20210721_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentform',
            name='document_file',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='consentformtemp',
            name='document_file',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='information',
            name='emergency_contactor_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='emergency_contactor_phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='employer_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='employer_occupation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='information',
            name='employer_phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='language',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='marital',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='pcp_facility_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='information',
            name='pcp_facility_city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='information',
            name='pcp_facility_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='pcp_facility_state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='information',
            name='pcp_facility_zip',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='pcp_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='pcp_phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='race',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='referred_by',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='statement_receiver_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='information',
            name='statement_receiver_city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='information',
            name='statement_receiver_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='statement_receiver_phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='statement_receiver_zip',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='informationtemp',
            name='emergency_contactor_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='informationtemp',
            name='emergency_contactor_phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='informationtemp',
            name='employer_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='informationtemp',
            name='employer_occupation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='informationtemp',
            name='employer_phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='informationtemp',
            name='language',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='informationtemp',
            name='marital',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='informationtemp',
            name='pcp_facility_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='informationtemp',
            name='pcp_facility_city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='informationtemp',
            name='pcp_facility_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='informationtemp',
            name='pcp_facility_state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='informationtemp',
            name='pcp_facility_zip',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='informationtemp',
            name='pcp_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='informationtemp',
            name='pcp_phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='informationtemp',
            name='race',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='informationtemp',
            name='referred_by',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='informationtemp',
            name='statement_receiver_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='informationtemp',
            name='statement_receiver_city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='informationtemp',
            name='statement_receiver_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='informationtemp',
            name='statement_receiver_phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='informationtemp',
            name='statement_receiver_zip',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='county',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_cell',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_home',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='signature',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_work',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), (
                'other', 'Other'), ('', '')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ssn',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profiletemp',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profiletemp',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profiletemp',
            name='county',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profiletemp',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profiletemp',
            name='phone_cell',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profiletemp',
            name='phone_home',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profiletemp',
            name='phone_work',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profiletemp',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), (
                'other', 'Other'), ('', '')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profiletemp',
            name='ssn',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profiletemp',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profiletemp',
            name='zip',
            field=models.CharField(default='', max_length=255),
        ),
    ]
