# Generated by Django 3.2.4 on 2021-07-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20210721_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profiletemp',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
    ]
